- src/App.js
- src/components/CreateProfileForm.js
- src/context/AuthContext.js
- src/helpers/stringUtils.js
- src/pages/Profile.js
- Adds profile page where users are able to update their personal information
> Add profile page

- src/components/NavBar.js
- Modify navbar to remove links if the person is logged (log in, sign up), and add links if the person is signed up (members, profile)
> Modify navbar

- package-lock.json
- package.json
- src/App.js
- src/index.css
- src/pages/Events.js
Review basic logic of events page including creating, deleting events for admins.
> added basic events page and logic with styling

- src/App.css
- src/index.css
- src/pages/Events.js
fixed styling and bugs regarding global css styling
> fixed styling and made calendar view the default

- src/App.js
- src/components/NavBar.js
- src/pages/Contactus.js
> Created contact us page

- src/pages/Contactus.js
> Contact Facebook page

- src/pages/Contactus.js
created a new link leading to the asop instagram page
> Contact IG Page

- src/pages/Contactus.js
> Added Directions to contact us page

- src/pages/Contactus.js
> Contact page titles

- src/pages/Contactus.js
realized I was working on an older broken version and buttons werent showing right
> Fixed buttons contact page

- src/pages/Home/Contact.js
- src/pages/Home/Home.css
- src/pages/Home/Home.js
I have added the contact section to the home page for members to get notification. However, I have not linked the button yet.
> Added Contact section to home page

- server/index.js
- src/App.css
- src/components/PaymentUpdate.js
- src/pages/Profile.js
Added the button to the profile page and when clicked it opens a stripe page with the "dues item" to sell. 
Still need to handle firebase logic and authentication.
> Added "pay dues" button/function to profile page

- package-lock.json
- package.json
- src/pages/Home/About.js
- src/pages/Home/Home.js
- src/pages/Home/Intro.js
I worked on some animation effect on the home page. This will bring some life into it.
> Added some animation effect

- src/pages/Home/Home.css
There was an image in the intro section that was not changing with the screen resolution changing. It is fixed :)
> Fixed a bug

- src/components/CreateProfileForm.js
- src/context/AuthContext.js
- src/helpers/stringUtils.js
- src/pages/Members.js
- src/pages/Profile.js
- Added a notifications field
- Whenever a user creates an account, a new notifications field is also pushed to firestore. This property dictates whether the user should receive event notifications or not.
- Removed age field from account creation
- Removed age field from account creation and as a property from firebase as this information can be derived from the users date of brith property.
> Add notifications property and remove age field on account creation

- src/pages/Members.js
- Removed variable from the dependency array in a useEffect hook that was causing infinite calls to be made to firebase.
> Remove updating element from dependency array making infinite calls

- src/App.css
- src/pages/Profile.js
- Removed the membership fee payment button if the user is currently an active member.
If currently an active member, the following message shows up:
Otherwise, the following option shows up:
> Remove membership payment option button if currently active paid member

- src/context/AuthContext.js
- src/pages/Members.js
- Allows admins to give/remove admin functionality from the members page.
> Add admin setting functionality

- src/index.css
- src/pages/Events.js
can now remove events from events page and it will remove from firestore
> added deleteDoc functionality that removes event from firestore

- src/pages/Events.js
events description now has capacity and maxCapacity
> added capacity and maxCapacity for RSVP purposes

- src/pages/Events.js
added ability for admins to see list of users who reserved an event, and fixed some handleCancelRSVP logic
> Events page

- package-lock.json
- package.json
- src/pages/Home/Footer.js
- src/pages/Home/Home.css
- src/pages/Home/Home.js
- src/pages/Home/Partner.css
- src/pages/Home/Partner.js
- src/pages/Home/Slider.js
I have linked all the footer, to their alternative pages and all the buttons on the home page work.
> Footer is done

- src/pages/Contactus.js
added logos to links for visuals
> Added logos

- server/package.json
simple PR, for some reason the package.json in the server folder wasn't being tracked by git.
> adding package.json file for server folder

- src/pages/Home/Home.js
Removed the current user id from Home
> Removed the current user id

- src/index.css
- src/pages/Events.js
just minor button design change
> minor UI changes

- server/temp.js
- src/index.css
- src/pages/Events.js
fixed reserve state bug, reverted button stylings to match other pages, created an alert for incorrect add event parameters, generated new SendGrid API key (the old one disappeared)
> events page bug fix, button styling fix, alert added, new api key
